# Generated by Django 5.2.14 on 2026-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0002_actualite_partenaire_structuresanitaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='programme',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='programmes/'),
        ),
        migrations.AddField(
            model_name='programme',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='programmes/'),
        ),
    ]
