# Generated by Django 5.2.14 on 2026-06-10 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0003_rename_image_programme_image1_programme_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuresanitaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuresanitaire',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='structuresanitaire',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='structuresanitaire',
            name='prefecture',
            field=models.CharField(default='Bangui', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuresanitaire',
            name='ville',
            field=models.CharField(default='Bangui', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuresanitaire',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
