# Generated by Django 5.2.14 on 2026-06-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0004_structuresanitaire_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='structuresanitaire',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='structuresanitaire',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='structuresanitaire',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='structures/'),
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='structuresanitaire',
            name='ville',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
