# Generated by Django 5.2.14 on 2026-06-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0005_contact_remove_structuresanitaire_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='traite',
        ),
        migrations.AddField(
            model_name='contact',
            name='corbeille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='reponse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('encours', 'En cours'), ('traite', 'Traité'), ('transfere', 'Transféré'), ('archive', 'Archivé')], default='nouveau', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='traite_par',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='transfere_a',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
