# Generated by Django 5.2.14 on 2026-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='traite_par',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='transfere_a',
        ),
        migrations.AddField(
            model_name='contact',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='transfert',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='statut',
            field=models.CharField(default='Nouveau', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sujet',
            field=models.CharField(max_length=255),
        ),
    ]
