# Generated by Django 5.2.14 on 2026-06-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0008_remove_contact_traite_par_remove_contact_transfere_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
