# Generated by Django 5.2.14 on 2026-06-23 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0009_activite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuresanitaire',
            name='prefecture',
            field=models.CharField(choices=[('Bangui', 'Bangui'), ('Ombella-Mpoko', 'Ombella-Mpoko'), ('Lobaye', 'Lobaye'), ('Mambere-Kadei', 'Mambere-Kadei'), ('Nana-Mambere', 'Nana-Mambere'), ('Sangha-Mbaere', 'Sangha-Mbaere'), ('Kemo', 'Kemo'), ('Ouaka', 'Ouaka'), ('Basse-Kotto', 'Basse-Kotto'), ('Mbomou', 'Mbomou'), ('Haut-Mbomou', 'Haut-Mbomou'), ('Vakaga', 'Vakaga'), ('Bamingui-Bangoran', 'Bamingui-Bangoran'), ('Nana-Grebizi', 'Nana-Grebizi'), ('Ouham', 'Ouham'), ('Ouham-Pende', 'Ouham-Pende'), ('Lim-Pende', 'Lim-Pende'), ('Haute-Kotto', 'Haute-Kotto'), ('Kotto', 'Kotto'), ('Mambéré', 'Mambéré')], max_length=100),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur')], default='ADMIN', max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
