# Generated by Django 5.2.14 on 2026-07-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0010_alter_structuresanitaire_prefecture_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur'), ('AGENT', 'Agent')], default='AGENT', max_length=20),
        ),
    ]
