# Generated by Django 5.2.14 on 2026-07-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0011_profil_actif_profil_photo_profil_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='actif',
        ),
    ]
