# Generated by Django 5.2.14 on 2026-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0012_remove_profil_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='auteur',
            field=models.CharField(default='CONASAN', max_length=100),
        ),
        migrations.AddField(
            model_name='actualite',
            name='categorie',
            field=models.CharField(default='Santé', max_length=120),
        ),
        migrations.AddField(
            model_name='actualite',
            name='vedette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actualite',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='titre',
            field=models.CharField(max_length=250),
        ),
    ]
