# Generated by Django 5.2.14 on 2026-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0013_actualite_auteur_actualite_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('histoire', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('valeurs', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='apropos/')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gouvernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('organigramme_pdf', models.FileField(blank=True, null=True, upload_to='organigrammes/')),
                ('image_organigramme', models.ImageField(blank=True, null=True, upload_to='organigrammes/')),
                ('image_president', models.ImageField(blank=True, null=True, upload_to='gouvernance/')),
                ('image_vice_president', models.ImageField(blank=True, null=True, upload_to='gouvernance/')),
                ('image_directeur', models.ImageField(blank=True, null=True, upload_to='gouvernance/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='videos/')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
