# Generated by Django 5.2.14 on 2026-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0014_apropos_documentation_galerie_gouvernance_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apropos',
            old_name='histoire',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='valeurs',
        ),
        migrations.AlterField(
            model_name='apropos',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apropos',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
