# Generated by Django 5.2.14 on 2026-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0015_rename_histoire_apropos_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apropos',
            options={'verbose_name': 'À propos', 'verbose_name_plural': 'À propos'},
        ),
        migrations.AddField(
            model_name='apropos',
            name='engagement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='historique',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='apropos/'),
        ),
        migrations.AddField(
            model_name='apropos',
            name='mot_president',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='objectifs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='organigramme_image',
            field=models.ImageField(blank=True, null=True, upload_to='organigramme/'),
        ),
        migrations.AddField(
            model_name='apropos',
            name='organigramme_pdf',
            field=models.FileField(blank=True, null=True, upload_to='organigramme/'),
        ),
        migrations.AddField(
            model_name='apropos',
            name='organigramme_word',
            field=models.FileField(blank=True, null=True, upload_to='organigramme/'),
        ),
        migrations.AddField(
            model_name='apropos',
            name='valeurs',
            field=models.TextField(blank=True),
        ),
    ]
