# Generated by Django 5.2.14 on 2026-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0016_alter_apropos_options_apropos_engagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='codis/')),
                ('nombre_fosa', models.PositiveIntegerField(default=0)),
                ('equipe_mobile', models.PositiveIntegerField(default=0)),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Dirigeant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gouvernance/')),
                ('biographie', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOrganigramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='organigramme/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='organigramme/')),
                ('word', models.FileField(blank=True, null=True, upload_to='organigramme/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
