# Generated by Django 5.2.14 on 2026-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0017_codis_dirigeant_documentorganigramme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GouvernanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('type_document', models.CharField(choices=[('organigramme', 'Organigramme'), ('decision', 'Décision'), ('rapport', 'Rapport'), ('proces_verbal', 'Procès-verbal'), ('note_service', 'Note de service'), ('autre', 'Autre')], default='organigramme', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='gouvernance/documents/')),
                ('image_apercu', models.ImageField(blank=True, null=True, upload_to='gouvernance/apercus/')),
                ('publier', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document de gouvernance',
                'verbose_name_plural': 'Documents de gouvernance',
                'ordering': ['-date_creation'],
            },
        ),
    ]
