# Generated by Django 5.2.14 on 2026-08-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0018_gouvernancedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('Rapport', 'Rapport'), ('Guide', 'Guide'), ('Procédure', 'Procédure'), ('Convention', 'Convention'), ('Formulaire', 'Formulaire'), ('Autre', 'Autre')], default='Autre', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/images/')),
                ('fichier', models.FileField(upload_to='documents/fichiers/')),
                ('public', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
