# Generated by Django 5.2.14 on 2026-08-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0019_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerie',
            options={'ordering': ['-date_creation']},
        ),
    ]
