# Generated by Django 5.2.14 on 2026-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0020_alter_galerie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerie',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Galerie'},
        ),
        migrations.AddField(
            model_name='galerie',
            name='categorie',
            field=models.CharField(default='Galerie', max_length=100),
        ),
        migrations.AddField(
            model_name='galerie',
            name='publier',
            field=models.BooleanField(default=True),
        ),
    ]
