# Generated by Django 5.2.14 on 2026-08-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0021_alter_galerie_options_galerie_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.TextField()),
                ('image_fond', models.ImageField(upload_to='hero/')),
                ('image_secondaire', models.ImageField(upload_to='hero/')),
                ('verset', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('texte_bouton1', models.CharField(default='Découvrir nos actions', max_length=80)),
                ('lien_bouton1', models.CharField(default='/programmes/', max_length=200)),
                ('texte_bouton2', models.CharField(default='Nous contacter', max_length=80)),
                ('lien_bouton2', models.CharField(default='/contact/', max_length=200)),
                ('publier', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='HeroAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_fond', models.ImageField(upload_to='hero/')),
                ('titre', models.CharField(default='Hero Accueil', max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Image de fond du Hero',
                'verbose_name_plural': 'Images de fond du Hero',
            },
        ),
    ]
