# Generated by Django 5.2.14 on 2026-08-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0022_hero_heroaccueil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroaccueil',
            options={},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='date_creation',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='heroaccueil',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='videos/miniatures/'),
        ),
    ]
