# Generated by Django 5.2.14 on 2026-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='programmes/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='programmes/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='programmes/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='programmes/')),
            ],
        ),
    ]
